name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: ckeckout
      uses: actions/checkout@v1

    - name: Login 
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: build and Push 
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: siwarmahfoudhi/app:latest